### ISSUE TITLE
How to generate swift code for custom (nested) GraphQL queries? 

### ISSUE THREAD

**Issue by returnzer0** [awslabs/aws-mobile-appsync-sdk-ios#146]
**Question**
I am following the example ChatQL app listed [here](https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular), my goal is to port it over to iOS. 

In the sample project written in Angular, there is a custom [query](https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular/blob/master/src/app/chat-app/graphql/queries/getUserConversationsConnection.ts) that grabs all the conversations which a user is currently participating in. I want to run the same query in swift but unfortunately, I am unable to create the nested query. For example, I am able to perform a `MeQuery()` and get `userConversations` from the results, but there is no option to iterate over the individual `userConversation` and get the `conversation` object or `associated` object.

**Code**
This is what the query looks like in Angular:
```
query getUserConversationConnectionThroughUser($after: String, $first: Int) {
  me {
    id
    registered
    __typename
    conversations(first: $first, after: $after) {
      __typename
      nextToken
      userConversations {
        __typename
        userId
        conversationId
        associated {
          __typename
          userId
        }
        conversation {
          __typename
          id
          name
        }
      }
    }
  }
}
```

This is what I have so far:

```
let convoQuery = MeQuery()

appSyncClient?.fetch(query: convoQuery, cachePolicy: CachePolicy.fetchIgnoringCacheData, resultHandler: { (result, error) in
    
    if let error = error {
        print("Error fetching conversations: \(error)")
    } else {
        
        if let userConversations = result?.data?.me?.conversations?.userConversations {
            for eachUserConversation in userConversations {
                        // eachUserConversation.conversation doesn't exist in here...
            }
        }
    }
    
})
```

All of my GraphQL query code is being generated via Amplify Codegen for iOS.

**Environment:**
 - AppSync SDK Version: 2.8.0
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0

**Device Information:**
 - Doesn't apply

**Comment by returnzer0** [comment]
Another way to summarize this problem is that my resolvers on type `UserConversation` for the fields `associated` and `conversation` are not showing up in the swift code, even though the resolvers are setup properly like the angular chat application.

**Comment by palpatim** [comment]
Thanks for the update @returnzer0. I'm investigating this and hope to have an answer for you soon.

**Comment by palpatim** [comment]
Hi @returnzer0,

Based on my understanding, this should be solved by this [CLI issue](https://github.com/aws-amplify/amplify-cli/issues/745), which had a [PR](https://github.com/aws-amplify/amplify-cli/pull/820) merged last week.

Can you update your local amplify CLI and see if regenerating your API code with the `max-depth` option fixes your issue?

**Comment by returnzer0** [comment]
Hi @palpatim, thanks for your response.

How do I specify the `max-depth` option?

**Comment by palpatim** [comment]
@returnzer0 

It looks like they just merged that in, actually--sorry for the premature notice.

You can update the CLI (`npm install -g @aws-amplify/cli`) to get the latest version, and specify during codegen as noted in [the docs](https://aws-amplify.github.io/docs/cli/codegen#statement-depth).

Alternately, you can specify a configuration value via `amplify codegen configure` to set the default value for all subsequent codegen operations.

Hope this helps.

**Comment by shannon-hager-skookum** [comment]
@returnzer0 
You may want to try adding a file to the generated graphQL files with your custom query. 
This is how we worked around this in order to avoid using a prerelease branch.
If you set up amplify codegen with the default options, you have a folder with the generated graphQL statements in files named `queries.graphql`, `mutations.graphql`, etc.
Create a new blank file in that folder and call it `customQueries.graphql` or something.
Copy the generated query from the `queries.graphql` file, paste it into `customQueries.graphql` then change the new query's name (can't have 2 queries with the same name, codegen will throw an error).
Then run `amplify codegen types` and amplify will generate the API.swift file again. It will use the generated graphql files in the folder as before but will also include your new query from the `customQueries.graphql` file.

**Comment by palpatim** [comment]
@returnzer0 

Did either the new CLI option or @shannon-hager-skookum's suggestion work for you?

**Comment by returnzer0** [comment]
Thank you both @palpatim and @shannon-hager-skookum, apologies for the late reply.

I didn't get around to tryig @shannon-hager-skookum's solution but the new `max-depth` option works perfectly.

I will close this issue now. Thanks again!

**Comment by EralpB** [comment]
Can you (or someone else!) please showcase your swift code, I updated max-depth but still cannot find how to pass field level arguments. @returnzer0

**Comment by returnzer0** [comment]
@EralpB Can you elaborate what you mean by field level arguments?

I am not using appsync anymore, but I can dig up an old project to show you an example.

**Comment by EralpB** [comment]
thank you @returnzer0 , very much appreciated!

I will go with the aws events example.


```
type Query {
	getEvent(id: ID!): Event
}

type Comment {
	# The id of the comment's parent event.
	eventId: ID!
	# A unique identifier for the comment.
	commentId: String!
	# The comment's content.
	content: String!
	# The comment timestamp. This field is indexed to enable sorted pagination.
	createdAt: String!
}

type CommentConnection {
	items: [Comment]
	nextToken: String
}

type Event {
	id: ID!
	name: String
	where: String
	when: String
	description: String
	# Paginate through all comments belonging to an individual post.
	comments(limit: Int, nextToken: String): CommentConnection
}
```

but the important part is:

```
type Query {
	getEvent(id: ID!): Event
}

type Event {
	id: ID!
	comments(limit: Int, nextToken: String): CommentConnection
}
```

now when I query an event, I get 1 page of comments, and I can theoretically paginate more by passing nextToken to the "comments" field. (that's what I mean by field-level parameters, while ID being query-level)

```
query getmyevent {
  getEvent(id: "70f73af9-3ea9-4ba8-b926-c6fa04205cc9") {
    id
    comments(limit: 1) {
      nextToken
    }
  }
}
```

in the AWS console, I can do that BUT auto-generated code in swift does not let me pass anything besides ID.. I'm feeling like this is a shortcoming of the code autogeneration. I want to do stuff like this and free-ly get data what I want and pass as many parameters as I want. what if comment had replies that are also paginated? 

```
query getmyevent {
  getEvent(id: "70f73af9-3ea9-4ba8-b926-c6fa04205cc9") {
    id
    comments(limit: 1) {
      items{
        commentId
      }
      nextToken
    }
  }
}
```


now since I've practiced a bit more, I see what you have done. I could do like you and add all my parameters to the query, but I felt like that was a hack, I love that fields can represent themselves in a self-contained way.


now I realize this is more like an iOS auto-generation question, but I think your feedback will be valuable for me/us to put this on track and follow graphQL best practices.

**Comment by returnzer0** [comment]
I agree with you 100% there is a shortcoming in the sdk. 

You can try the method that you mentioned, which as you said is a shortcoming, but if you are already invested into development, you, unfortunately, don't have any other choice.

With appsync, I think that the team is quite bright but also small. So they are more focused on adding more features instead of ironing the current ones.

If you look at some other issues that I have opened, you can see that the web console acts quite a lot different than what the sdk is supposed to do.


I have also realized that with the ios autogen code, you sometimes need to have different initializers for different values and try to eliminate any optional parameters in the graphql query as much as you can, it will make your life easier.

Best of luck.

**Comment by jangelsb** [comment]
I just wanted to expand upon @shannon-hager-skookum 's comment a little bit because I was still having trouble knowing where to place files and whatnot. 

In our test app there is a generated folder called `graphql` where the auto generated queries reside:
<img width="423" alt="Screen Shot 2020-06-19 at 6 16 10 PM" src="https://user-images.githubusercontent.com/11953370/85188124-874c9d00-b259-11ea-80cb-497d0679c80a.png">

I put custom queries in a file in that folder, `custom_queries.graphql`, as seen above. The contents of this file are just simple queries, for example:
```
query Test {
  getEvent {
    title
    description
  }
}
```

Then make sure you are in the directory where the `schema.graphql` file resides and  just run `amplify codegen`

This will generate the queries in the `AppSyncAPI.swift`

I hope this helps anyone us that stumbles upon this question in the future.
