### ISSUE TITLE
Get other user's attributes by its id/username through AWSMobileClient

### ISSUE THREAD

**Issue by medvedNick** [awslabs/aws-mobile-appsync-sdk-ios#154]
I'm making an iOS app using amplify. Auth is performed using Cognito, and the database is Appsync GraphQL.

There is a `Post` entity in the database, which has `userID` attribute got from Cognito. I'd like to show creator's info in that `Post` in app UI. For example, `username` and a few other attributes from Cognito user (like profile picture).

Is there any way I can achieve this? I do not see any methods to fetch other users details neither in `AWSMobileClient`, nor in `AWSCognitoIdentityUserPool`. Or should I create a separate entity `user` to be able to access it with AppSync?

**Comment by palpatim** [comment]
Hi @medvedNick,

My initial thoughts:

Regardless of the data source, you'd probably want to create a `User` or `UserProfile` type in your app's schema that would allow you to query it via GraphQL. (You'd obviously want to ensure that only publicly viewable data gets shadowed.)

The source of the data could be app storage (e.g., your app's DynamoDB table if you're using that) that you populate when a user completes registration for your app. You would also have to consider how you want to keep that data in sync--what happens when the user changes their profile picture?

Otherwise, you could set up a Lambda data source that queries your Cognito backend using an [`AdminGetUser`](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminGetUser.html) call when the resolver is invoked. The upside is that it keeps data synchronized. The downside is that it might be more complex to set up, and more expensive to run since it involves both Lambda and Cognito calls for every invocation of the resolver.

I'll reply back on this thread if I come up with any other approaches after discussions with other folks.

**Comment by medvedNick** [comment]
@palpatim sounds reasonable, thank you

**Comment by palpatim** [comment]
@medvedNick 

After some more discussion with the team, I’ve confirmed that "shadowing" the profile data is the better solution; we generally don’t want AdminGetUser calls used for arbitrary queries of data. If your use case is sufficiently relaxed about the synchronization of profile data, one approach might be to update your AppSync profile store when the customer logs in. Practically speaking, it may be that you've configured the app in such a way that the only way to update the profile data is via your app, which means you'll know immediately if a customer changes.

Hope this helps.

**Comment by palpatim** [comment]
@nikhil-dabhade 

Any recommendations from your perspective on how a developer could accomplish this use case?

**Comment by undefobj** [comment]
I would recommend that you do this through the GraphQL transform: https://aws-amplify.github.io/docs/cli/graphql?sdk=ios
Rather than treating Cognito as a database (it is not) I would store the creator of the post's information as a field in the object which is persisted into DynamoDB when using `@model`. This could either be via an input field or you could do it in the background automatically in the GraphQL resolver. Right now doing that automatically in the resolver would need to be by hand in the console however custom resolvers will be merged in the coming weeks which would allow you to do this in your CLI project too: https://github.com/aws-amplify/amplify-cli/pull/581
