### ISSUE TITLE
Mutations with large inputs causes high CPU usage and the UI to freeze

### ISSUE THREAD

**Issue by btn52396** [awslabs/aws-mobile-appsync-sdk-ios#162]
**Describe the bug**
I have a use case where I need to send a mutation every other second in the background. This works fine on the simulator but when I run the code on a physical device, the UI freezes for a split second when a mutation is being sent. This causes a frustrating user experience

**To Reproduce**
1. Create a loop that runs a mutation every 2 seconds(The mutations must have a large input. The character length of each of my inputs are about 600-1000 characters in total. If the input is small the UI does not freeze)
2. When the mutation is ran try using the UI such as scrolling through a table
3. The UI will freeze for a split second while the mutation is being performed

**Expected behavior**
The UI should be responsive even when a mutation is being performed

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.9.2
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information (please complete the following information):**
 - Device: iPhone 8
 - iOS Version: 12.1.2
 - Specific to simulators: No

**Comment by palpatim** [comment]
Hi @btn52396,

Thanks for reporting the issue, and please feel free to reopen if you're able to reliably reproduce. I will note that in 2.9.2, we fixed a bug that was dispatching all subscription callback messages on the main queue instead of using the supplied handler queue. That may have impacted your main thread performance, depending on the code path you were using. 

On a similar note, many AppSync functions take a queue parameter on which the callbacks should be invoked. Those queues tend to default to `DispatchQueue.main` since they're often used to update UI, but if a caller does significant work on them, it may impact performance.

Finally, it may be that you're simply encountering a bug in our code triggered by large payloads, which would require investigation by us. Do let us know if you see anything that points to that and we'll take a look.

Thanks!

**Comment by btn52396** [comment]
I've been testing this for the past few days now and found that it's easier to reproduce this bug when authenticating with Cognito. Can you see if you can reproduce it by logging in with Cognito and then send mutations with a large payload(>1000 characters each) in quick succession? For example, try running 1000 mutations in succession and see if the CPU spikes, rendering the UI laggy. I also find if I rerun the app and run the mutations again a second time, the CPU usage is much worse the second time around and can get to 100% usage. My use case involves IOT devices so I need to rapidly send data in the background without affecting the UI. Please let me know if you can replicate this and if there is a possible solution to improve the mutation queue

**Comment by palpatim** [comment]
@btn52396 

Thanks for the update. Did you close this issue because you identified a root cause unrelated to the SDK, or because you don't have solid repro on this? If the latter, I'd like to reopen this as a bug so we can track the issue and try to come up with test cases that might repro this locally. I can't say exactly when we'd be able to get to it, but I don't want it to fall off our radar.

**Comment by btn52396** [comment]
@palpatim  Ah yeah I forgot. I was going to open a new issue because after a lot of investigation my description of the bug wasn't accurate. I don't think it has much to do with payload size. It has more to do with sending mutations in succession. I'll create a new issue describing the problem, my temporary solution to it, and exactly where in the SDK for you guys to look at
