### ISSUE TITLE
how to handle the reconnection logics?

### ISSUE THREAD

**Issue by fans3210** [awslabs/aws-mobile-appsync-sdk-ios#17]
Currently I have my subscription code in viewDidload. The app's subscription won't work if app was in background for a few minutes the back to foreground. But I'm still able to fire mutation actions. How should I handle the reconnection to make the subscription work again?

**Comment by AlexHmelevskiAG** [comment]
As long as we have the same issue I'll add our comments here instead of opening a new issue. There are 2 problems/question we have with subscription: 
1. when the app goes to the background and stays there for at least a minute the subscription might not pick up, most likely won't pick up. During our POC we where using simulator to prove that subscription is working for this case. However simulator has different limitation and technically there is no real background mode. So to see the problem need to test the issue on the device. 

 From the comments in the code of `MQTTClient.h` I see that 
> These properties control the reconnect behavior of the MQTT Client.  If the MQTT
 client becomes disconnected, it will attempt to reconnect after a quiet period;
 this quiet period doubles with each reconnection attempt, e.g. 1 seconds, 2
 seconds, 2, 8, 16, 32, etc... up until a maximum reconnection time is reached.

I question myself what's happening if the max amount is reached and what the the maximum amount equal to? Do you terminated the connection and never pick it up after it's being reached? We receive the error saying "Subscription Terminated"

Also I couldn't find that you track the app events: going background / foreground, maybe it's not designed.

2.  If it reconnects can we expect that missing events will be sent to the client or not? It looks like they are not sent.

**Comment by fans3210** [comment]
I'm still not familiar with appsync thus might be wrong. Made a few more attempts and found that the subscription expired even when the app is still in foreground without any event after a few minutes. I don't see any delegation method that can let the user being informed when the connection is lost. Is it possible to let the user at least informed thus we can re-make the subscription again when connect lost?

**Comment by AlexHmelevskiAG** [comment]
@fans3210 you should receive an error in the subscription callback.

**Comment by fans3210** [comment]
@AlexHmelevskiAG , thank you. So I should manually call the subscribe function again while received the disconnected error feedback to make the reconnection right?

**Comment by AlexHmelevskiAG** [comment]
@fans3210 That's what we trying to figure out :) 
Well probably we will do on our side the next thing. When you go to background - you unsubscribe and when go to foreground subscribe again. If you don't care much about missing events during being in the background - the case will work for you.

**Comment by rohandubal** [comment]
Hello @fans3210 @AlexHmelevskiAG 

What @AlexHmelevskiAG is saying above, would be a good intermediate solution to make sure the subscriptions are received when the app is in foreground. Although I believe in addition to it a query from network should also run to ensure missed messages/

As a long term, we could have a type of query/ subscription which when called would internally run a query getting last `n` messages/records. This would to good extent make sure the data is up-to-date. This new operation could also detect background events, subscription termination, etc. so that the app does not have to deal with such events. The subscriber will always keep getting events(The SDK does the resubscription.) Does that sound an approach which would help you?

Thanks
Rohan

**Comment by AlexHmelevskiAG** [comment]
Hello @rohandubal 
It might work, probably instead of getting last n messages, you could use timestamp. For example when the app goes to background you save timestamp T1 locally, when wakes up (T2). You ask server for getting the messages/records that were added/modified between T1 and T2. That means all the records should contain the attribute of last update timestamp. What do you think? It will help to return all the missed events and not just N of the last since the client doesn't know how many it has missed, right?


Btw, any timeline on solution for this issue?
Thank you.

**Comment by fans3210** [comment]
@rohandubal . I found that after a subscription method is called, there is no immediate callback to tell us whether the connection success. I only know whether there is error since the result block will return me the error immediately. Is it possible to let us notified that the connection is successful? We need to manage the msg sync for each disconnect -> connect window

**Comment by rohandubal** [comment]
Hello @fans3210 

That would probably be good utility to add a connection acknowledgement. could you please open a separate issue where we can track that?

Thanks
Rohan

**Comment by fans3210** [comment]
Thanks @rohandubal will do that
