### ISSUE TITLE
Is AWSMobileClient the preferred way to integration AppSync and Cognito User Pools?

### ISSUE THREAD

**Issue by shannon-hager-skookum** [awslabs/aws-mobile-appsync-sdk-ios#183]
AppSync early adopters had implemented the Cognito User Pool + AppSync functionality based on documentation collected from several sources (questions here, Cognito docs, etc) and were never really given the example implementation promised last March. The documentation has now been moved to Amplify and the docs appear to recommend using AWSMobileClient in addition to Cognito and AppSync in order to leverage some of the more recent updates to the SDKs.

My question is: Should we add AWSMobileClient to our AppSync project and refactor our Cognito User Pools integration? Is AWSMobileClient a de facto requirement now for AppSync + Cognito User Pools if not an actual requirement? Are there reasons we should or should not use AWSMobileClient?

**Comment by palpatim** [comment]
I'm assigning this to @undefobj to see if he can give an authoritative recommendation, as he is driving much of the work around the auth enhancements and might be able to provide a broader perspective, since he's also driving the RFC for the Admin enhancements and flows and has worked on auth across all platforms.

To underscore your point about AWSMobileClient, though: if you haven't already seen it, please look at [the Auth RFC](https://github.com/aws-amplify/aws-sdk-ios/issues/1158) where we're soliciting customer feedback enhancements to AWSMobileClient. That said, we continue to answer questions and address bugs in the non-mobile-client SDKs.

**Comment by undefobj** [comment]
In the near future, yes we will recommend using the `AWSMobileClient` as the way to handle authentication for all of the service interactions with iOS and Android, not just AppSync. The only reason it isn't the only answer at the moment is because there are still a few gaps that we will be closing as referenced in these two RFCs that @palpatim mentioned:

https://github.com/aws-amplify/aws-sdk-ios/issues/1158
https://github.com/aws-amplify/aws-sdk-android/issues/634

We'll deliver these in a couple of phases, with the first being functional equivalency with the multiple Cognito SDKs from a client API perspective. The second phase will address more customization around "Drop-In UI". While I cannot guarantee any dates, we're trying to deliver the first phase in the next couple months.

To the question on should you refactor - It really does depend. On the one hand if your app is working and you won't be adding any new functionality, you might want to leave it as is. However if things are still in flux or you weren't able to accomplish something in the past it might be a good idea to refactor. For instance there are many features around state management and offline capabilities that we added to the `AWSMobileClient` which you would have had to code yourself in the past: https://aws-amplify.github.io/docs/ios/authentication#how-it-works. We're going to have more stuff done automatically for you in the next phase such as OAuth redirection with the Cognito Hosted UI and federation of social providers. 

One of the things that we are trying to move towards in the iOS/Android space is a similar "category based programming model" that we introduced in the mobile web & hybrid app ecosystem, allowing you to focus on your app code or business logic and less time learning all of the services. So you can program using the "Auth" or "Storage" or "API" categories and use simple, declarative methods rather than learn all of the implementations. We'll do all the common routines (like the features I mentioned above) in these categories by encoding them as best practices. The `AWSMobileClient` is a first move in this direction for iOS and Android and we'll expand this over the course of the year. So bringing this back to the refactor question, it might not be necessary for you right now or you might want to wait until the next phase of `AWSMobileClient` Auth features release in the next couple months, or you might want to wait until later this year to see how the other category implementations play out.
