### ISSUE TITLE
AWSAppSyncClient eating requests with expired user pool token

### ISSUE THREAD

**Issue by zigfreid5** [awslabs/aws-mobile-appsync-sdk-ios#185]
Similar to the behavior mentioned in #91, the callback for a fetch is never called if the user pool token has expired.

There might be a few different things in play here, but I am using the AWSMobileClient as the credentials provider for the AWSAppSync Client.

**To Reproduce**
1. If the user pools token has expired, the mobileClient will still have a userState of .signedIn on initialization. **<- Possible problem? Shouldn't an expired token be known upon initialization?**

```swift
_mobileClient.initialize { [weak self] (userState, error) in
    if let userState = userState {
        switch userState {
        case .signedIn: print("Signed in")
        case .signedOut: print("Signed out")
        case .signedOutFederatedTokensInvalid: print("Signed out fed tokens invalid")
        case .signedOutUserPoolsTokenInvalid: print("Signed out user pools token invalid")
        case .guest: print("Guest")
        case .unknown: print("Unknown")
    }
}
```

2. The appSyncClient has no issues initializing with a client configuration that uses the mobile client as a credentials provider
```swift
let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: AWSAppSyncServiceConfig(),
                                                      credentialsProvider: LoginManager.shared._mobileClient,
                                                      cacheConfiguration: cacheConfiguration)
```

3. Data can be restored with appSyncClient from cache with no issue
4. A call to fetch a query from the server will never call the completion handler **<- This is the issue**
5. The mobileClient user state listener will be called with the .signedOutUserPoolsTokenInvalid state
6. If not handled in the mobileClient user state listener, the behavior listed above will repeat on every launch of the application.

**Expected behavior**
The callback should be called with an error indicating the user is unauthorized

**Environment:**
 - AppSync SDK Version: (2.10.0)
 - AWSCore (2.8.4)
 - AWSAuthCore (2.8.4)
 - AWSMobileClient (2.8.4)
 - Dependency Manager: Cocoapods
 - Swift Version : 4.2

**Device Information:**
 - Device: iPhone XS Max
 - iOS Version: 12.1.4
 - Specific to simulators: No

**Comment by palpatim** [comment]
@zigfreid5 

Thanks for the report. The fact that we don't get a callback in the `fetch` completion handler does seem like a bug, but I want to verify the expected behavior with my colleagues who are closer to the mobile client code. I'll also verify the expected behavior on initialization with an expired token.

I'll update this issue when I have more info.

**Comment by palpatim** [comment]
@zigfreid5 

It turns out that both of these are expected behaviors.

1. During initialization, the "signed in" state is determined solely by the *presence* of the token, as opposed to the *contents or validity* of the token. I'm going to open a feature request on the MobileClient to change that behavior, since it seems reasonable (at least from my perspective) that we'd want consistent behavior between token fetching and initialization. Since there may be use cases I'm not considering, we'll see what they say.
1. During fetch, the MobileClient behavior is to block waiting calls until we get a valid sign in state. The expected resolution in the auth state listener is to either invoke the signIn flow, or to call [releaseSignInWait()](https://aws-amplify.github.io/aws-sdk-ios/docs/reference/AWSMobileClient/Classes/AWSMobileClient.html#/s:15AWSMobileClientAAC17releaseSignInWaityyF) to cancel the calls, at which point you should call sign out. You're not the only person to be confused by this. We've got a docs issue open to make that clearer: https://github.com/aws-amplify/docs/issues/414
