### ISSUE TITLE
Cocoapods is broken

### ISSUE THREAD

**Issue by rcfrias** [awslabs/aws-mobile-appsync-sdk-ios#2]
After pod install, the error is the following:

pod install
Analyzing dependencies
[!] Unable to find a specification for `AWSAppSync (~> 2.6.7)`

[!] Automatically assigning platform ios with version 10.0 on target EventsApp because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

**I think the readme should be updated too.**

**Comment by kvasukib** [comment]
Hi @rcfrias, Did you run `pod repo update` before attempting to run `pod install`?

**Comment by kredden** [comment]
Hi, it is normal to define your platform in the pod file, you must not have, which is why you are getting that message.  The default pod file that is created when you do a pod init for a project has that in it although it is commented out, it will look something like this:

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestProject

end

If you uncomment it out by removing the # you will not see that warning.

We will track the "Unable to find specification for  AWSAPpSync" issue in your other ticket (https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios/issues/4).

Regards,
Kevin

**Comment by rcfrias** [comment]
@kvasukib this was definitely the fix for the issue.  Thankx for the prompt response!  Hopefully this is included in the documentation.
