### ISSUE TITLE
Getting "Software caused connection abort" while fetching query when app became active

### ISSUE THREAD

**Issue by dreamBegin** [awslabs/aws-mobile-appsync-sdk-ios#201]
Getting this error **"Software caused connection abort"** while fetching a query from Appsync. This query works perfect every-time, I only get this error when I minimize my app and receive the push and when I open the app by tapping on the push I fire a AppSync query sometimes it works and sometime I receive this error in the response : - 

Error object : **Optional<Error>
  ▿ some : AWSAppSyncClientError
    ▿ requestFailed : 3 elements
      - .0 : nil
      - .1 : nil
      ▿ .2 : Optional<Error>
        - some : Error Domain=NSPOSIXErrorDomain Code=53 "Software caused connection abort" UserInfo={_kCFStreamErrorCodeKey=53, _kCFStreamErrorDomainKey=1}**

Apologies if the issue already have been found or reported because i didn't find anything yet. Can you tell me what is the reason behind that and feel free to let me know you if you need more information on this issue.
Thanks.

**Comment by rohandubal** [comment]
Hello @dreamBegin 

Sorry that you are having issues using the SDK. I did some search around this error and it looks like this is a bug on Apple's side. You can access the bug report that is filed here: https://bugreport.apple.com/web/?problemID=43882930 

It would probably difficult for us to fix this since we use URLSession underneath. Some developers were able to fix this by adding a small delay before executing the network call once the device comes foreground.

Hope this helps,
Rohan

**Comment by dreamBegin** [comment]
Thank you for the response @rohandubal 
Actually I realized that earlier the it was happening/not happening with the delay for example when i had my break point on it always worked and was not working when I load the app instantly. I added delay and it worked but I Thought lets see if we have any other alternate. So I'm going with the delay solution.

Thanks and Regards
Kuldeep Tanwar
