### ISSUE TITLE
Subscribe not work

### ISSUE THREAD

**Issue by LuoDengfeng** [awslabs/aws-mobile-appsync-sdk-ios#207]
appSyncClient fetch and perform(mutation:) method works well, but the appSyncClient?.subscribe(...) method not work, can not response when other one create, update or delete data. What seems to be the reason of the issue? Have I ignored some configuration?

**Comment by minbi** [comment]
Hi @LuoDengfeng ,

We can help you solve the problem, but we need some more information.

What does your Cocoapod file dependencies look like? Can you provide a code sample of your subscription? What does your schema look like? and how was it generated?

**Comment by LuoDengfeng** [comment]
Podfile:
`platform :ios, '10.0'
use_frameworks!
targetsArray = ['TestAppsync']
targetsArray.each do |t|
    target t do
    pod 'AWSAppSync'
    end
end`
Code sample:
CreateMutation: `let nickname = "luo"
        let mutationInput = CreateAuthorInput(nickname: nickname)
        
        appSyncClient?.perform(mutation: CreateAuthorMutation(input: mutationInput)) { (result, error) in
            if let result = result {
                print(result.data!.createAuthor?.id)
            } else if let error = error as? AWSAppSyncClientError {
             
            }
            if let resultError = result?.errors {

            }
        }`
Subscribe:`subscriptionWatcher = try appSyncClient?.subscribe(subscription: OnCreateAuthorSubscription()) {
                (result, transaction, error) in
                if let result = result {
                    print(result.data!.onCreateAuthor!.nickname)
                    self.mutationBtn.setTitle(result.data!.onCreateAuthor!.nickname, for: .normal)
                } else if let error = error {
                    print(error.localizedDescription)
                }
            }`
Finally the createMutation works well, I can find the created data in DynamoDB, but the subscribe did not work. Please help me find the reason, also I attach the schema here, you can check if anything wrong with it.
[schema.json.zip](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/files/3006162/schema.json.zip)

**Comment by LuoDengfeng** [comment]
I have tried your sample project EventsApp, the subscribe works. I can't figure out what's wrong with my own project. Should it be the schema reason? Should I config something in the console to make the  subscribe work?

**Comment by amuresia** [comment]
I seem to be experiencing the same problem, where queries and mutations work, but not subscriptions.
I've got it to work in a legacy UIViewController but it doesn't seem to work with Apple's new framework Combine.

When I step through the code in the debugger I can see that the subscription is called
```            watcher = try appSyncClient?.subscribe(subscription: OnCreateRentalSubscription(),
                                                   resultHandler: { (resultIn, trans, error) in
```
But then it jumps out to the catch and doesn't execute that either, some reading suggests that it's because the operation doesn't return an error that can be caught but rather an exception that it cannot recover from.

However, if I use the UIViewController class instead of Combine, it seems to work, but then my SwiftUI View is not updated when the subscription is triggered by adding a new item
```
            ForEach(self.rentals, id: \.id){ rental in
````
I tried different approaches but even the simplest that is available in the docs, doesn't work
```
func subscribetoUserRental() {
    //Set a variable to discard at the class level
    var discard: AWSAppSync.Cancellable?
    let appDelegate = UIApplication.shared.delegate as! AppDelegate
    let appSyncClient = appDelegate.appSyncClient
    //In your app code
    do {
        discard = try appSyncClient?.subscribe(subscription: OnCreateRentalSubscription(), resultHandler: { (result, transaction, error) in
            if let result = result {
                print(result.data!.onCreateRental!.name + " " + result.data!.onCreateRental!.description)
            } else if let error = error {
            print(error.localizedDescription)
            }
        })
        } catch {
        print("Error starting subscription.")
    }
}
```
The logs are not particularly helpful either:
```
2019-08-10 17:45:07:729 proj[96207:11368930] Merging 4 records
2019-08-10 17:45:07:771 proj[96207:11368925] Merging 26 records
2019-08-10 17:45:07:772 proj[96207:11368789] Subscribing to operation proj.OnCreateRentalSubscription
2019-08-10 17:45:07:772 proj[96207:11368789] Stopping watcher 1
```

**Comment by palpatim** [comment]
Since this issue is quite old at this point I'm going to close it even though we never resolved it. We've made significant improvements to the underlying subscription management in the intervening time, as well as introducing Amplify DataStore to simplify the management of subscriptions, so it's possible that the original issue no longer pertains in any event. If you continue to have problems with AppSync subscriptions, please open a new bug in this repo with appropriate details.
