### ISSUE TITLE
Giving appSyncClient configuration with userPoolsAuthProvider using Cognito authentication causing memory leak

### ISSUE THREAD

**Issue by uhive-genie9** [awslabs/aws-mobile-appsync-sdk-ios#227]
**How to give appsyncClient configuration using userPoolsAuthProvider?**
- im using Cognito authentication, and im getting the access token from the server
- my purpose here is that i want to use access token instead of the AWSMobileClient.
- my concern is that this is causing memory issues

**This is my Auth Class sample:**
```
class AuthClient: AWSCognitoUserPoolsAuthProvider {
    
    func getLatestAuthToken() -> String {
        
        return "MyAccessToken"
    }
}
```

**Screenshots**
<img width="1450" alt="Screen Shot 2019-04-11 at 12 56 21 PM" src="https://user-images.githubusercontent.com/49156414/55948482-50442a00-5c59-11e9-8000-98636d39f9b4.png">
<img width="1286" alt="Screen Shot 2019-04-11 at 1 06 32 PM" src="https://user-images.githubusercontent.com/49156414/55949158-a6659d00-5c5a-11e9-8dfd-bc3da75aab9c.png">

**Environment:**
 - AppSync SDK Version: 2.10.3
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information :**
 - Device: iPhone SE
 - iOS Version: 12.1.4

**Comment by ahmedAlmasri** [comment]
+1

**Comment by uhive-genie9** [comment]
This issue has been opened for 19 days, and no action nor update is being taken 
@muellerfr  why did you change the label to a question? It's clearly a **bug**, not a question.

**Comment by palpatim** [comment]
@uhive-genie9 

We are investigating this now and will update as soon as we have more information or questions.

Also, can you clarify your use case a bit? What steps are you taking to see this behavior? For example, if you're seeing two app sync clients, are you actually creating two clients, or are you saying that something in the auth flow is instantiating another client object?

**Comment by uhive-genie9** [comment]
Hello @palpatim,

### What i'm trying to accomplish here:
Is to **configure the AWSAppSyncClient**, **call my mutations**, **queries and subscriptions** without getting retained cycles/ memory leaks

### What i have made:

- what i'm doing is very basic, i have a class for AWSAppSync called **AWSAmplifyHelper** where i place my mutations and configurations(a helper file).

#### Please note that:
- **AWSAmplifyHelper** is not a singleton, its a normal basic class where i need to instantiate an object of it in order to configure the **AWSAppSyncClient** and to access its functionalities.

I use the following code to configure the **AWSAppSyncClient**: (check the code snippet)


```
    private var appSyncClient: AWSAppSyncClient? //class level variable

    func configureAmplify() {
 
        do {
            // You can choose the directory in which AppSync stores its persistent cache databases
            let cacheConfiguration = try AWSAppSyncCacheConfiguration()
            
            // AppSync configuration & client initialization
            let appSyncServiceConfig = try AWSAppSyncServiceConfig()
            
            
            let appSyncConfig = try AWSAppSyncClientConfiguration(appSyncServiceConfig: appSyncServiceConfig,
                                                                  userPoolsAuthProvider: UserPoolAuthProviderHelper(), cacheConfiguration: cacheConfiguration,
                                                                  connectionStateChangeHandler: nil)
            
            
            appSyncClient = try AWSAppSyncClient(appSyncConfig: appSyncConfig)
            
            // Set id as the cache key for objects. See architecture section for details
            appSyncClient?.apolloClient?.cacheKeyForObject = { $0["id"] }
            
        } catch AWSAppSyncClientError.requestFailed(_, _, _){
            print("requestFailed")
        } catch AWSAppSyncClientError.authenticationError(_) {
            print("authenticationError")
        } catch AWSAppSyncClientError.noData(_) {
            print("noData")
        } catch AWSAppSyncClientError.parseError(_, _, _) {
            print("parseError")
        } catch let error {
            print("general error: \(error)")
        }
        
    }
```

- the **userPoolsAuthProvider** which is used in the intializer is a custom class which conforms to **AWSCognitoUserPoolsAuthProvider**

```
import Foundation
import AWSAppSync

//MARK: - TOKEN

class UserPoolAuthProviderHelper: AWSCognitoUserPoolsAuthProvider {
    
    func getLatestAuthToken() -> String {
        return UserDefaults.standard.string(forKey: "AccessToken") ?? ""
    }
    
}
```

### How the memory issues are being produced (multiple cases where memory leaks are being introduced)?

##### case 1: Configuring the AWSAppSyncClient leak:

1. instantiate an object of the **AWSAppSyncHelper**.
2. configure the **AWSAppSyncClient** using the **configureAmplify** function which is explained above.

##### case 2: Configuring the AWSAppSyncClient leak:

1. instantiate an object of the **AWSAppSyncHelper**.
2. configure the **AWSAppSyncClient** using the **configureAmplify** function which is explained above.
3. using the appSyncClient?.perform(..) function for example to perform a mutation as **follows**:

```
    /// send message mutation main Function
    
    ///
    /// - Parameters:
    ///   - queue: the queue on which the mutation runs on
    ///   - optimisticUpdate:
    ///   - receiverId: the receiver's id
    ///   - conversationId: the conversation's id
    ///   - messageType: message type as enum
    ///   - text: text
    ///   - url: url
    ///   - senderId: the sender's id
    ///   - completion: the success or the fail of the mutation
    private func addMessageMutation(queue: DispatchQueue = .main, optimisticUpdate: OptimisticResponseBlock? = nil, receiverId: Int, conversationId: Int, messageType: MsgType = .text, text: String, url: String?, senderId: Int, completion: @escaping ((Result<GraphQLResult<AddMessageBiConversationMutation.Data>?>, Int?) -> Void)) {
        
        let mutation = AddMessageBiConversationMutation(receiver_user_id: receiverId,
                                                        user_id: senderId,
                                                        conversation_id: conversationId,
                                                        m_type: messageType.rawValue,
                                                        text: text,
                                                        url: url)
       
        appSyncClient?.perform(mutation: mutation, queue: queue, optimisticUpdate: optimisticUpdate, resultHandler: { (result, error) in
            
            guard let result = result else {
                guard let error = error else {return}
                completion(.failure(error), nil); return}
            
            completion(.success(result), result.data?.addMessageBiConversation?.message?.messageId)
            
        })
        
    }

    /// Send message mutation
    ///
    /// - Parameters:
    ///   - receiverId: the receive's id
    ///   - senderId: the sender's id
    ///   - conversationId: the conversation id
    ///   - text: the actual text
    ///   - url: the url if found
    func sendTextMessageMutation(receiverId: Int, senderId: Int, conversationId: Int, text: String, url: String? = nil, completion: @escaping(Int?) -> Void) {
        
        self.addMessageMutation(receiverId: receiverId, conversationId: conversationId, text: text, url: url, senderId: senderId) { (result,msgId)  in
            switch result {
            case .success(let value):
                print(value as Any)
                completion(msgId)
            case .failure(let error):
                print(error)
                completion(nil)

            }
        }
    }
```

in the above two cases almost more than 42 memory leak is being introduced.

**Comment by palpatim** [comment]
@uhive-genie9 

I've attempted to repro this a few different ways without success. I'm able to see leaks, but none related to the AppSync client code path (at least as far as I can tell)

Please take a look at my fork of the [AppSync Events Starter Sample](https://github.com/palpatim/aws-mobile-appsync-events-starter-ios/tree/palpatim/gh-227-memory-leak) and compare it to your app code to see if I'm doing something different in my setup that would contribute to the different behavior.

**Comment by uhive-genie9** [comment]
@palpatim  will give it a shot and get back to you

**Comment by uhive-genie9** [comment]
@palpatim please note that i mentioned using the  # **cognito** **authentication**, your sample is API key based, this issue only occurs using cognito authentication.

**Comment by palpatim** [comment]
@uhive-genie9 Sorry for the confusion: The `awsconfiguration.json` committed as part of the code repo does specify `API_KEY` as the authentication mode, but I used `AMAZON_COGNITO_USER_POOLS` during testing. Please see the file `awsconfiguration.json.TEMPLATE` for the configuration I used (minus account-specific values).

**Comment by uhive-genie9** [comment]
i've noticed that in the appDelegate youre using  the **AWSCognitoIdentityUserPool** to get the user accessToken, im not following that approach, instead i'm getting the user accessToken from the serverside

<img width="779" alt="Screen Shot 2019-05-14 at 3 19 52 PM" src="https://user-images.githubusercontent.com/49156414/57697407-cc1c0280-765b-11e9-8f7a-deb5bf038421.png">

**Comment by uhive-genie9** [comment]
any update? i still have not got any luck here .

**Comment by palpatim** [comment]
I am investigating but still am not able to repro. I want to try a couple more things. I will update later today with whatever status I have.

**Comment by palpatim** [comment]
@uhive-genie9 

I'm still unable to see this behavior, but I'm also confused by your statements:

> i've noticed that in the appDelegate youre using the AWSCognitoIdentityUserPool to get the user accessToken, im not following that approach, instead i'm getting the user accessToken from the serverside

1. What leads you to believe that it's the usage of a `AWSCognitoUserPoolsAuthProvider` that is causing the leaks? If you remove all of that code and test with an `API_KEY` auth mode, does the problem go away?

1. How exactly are you retrieving the access token from the server? If you're using a hand-rolled mechanism for retrieving the token, there may be a retain cycle in that code you're not seeing. In any case, making a network call to retrieve the token on demand, assuming it's properly isolated from other parts of the system and not retained (or retaining) in unexpected ways, should be doing largely the same thing my sample is doing. My sample uses the recommended API (`currentUser().getSession()...`) which may retrieve a cached result from the local device, but it does hit the network if the access token is expired.

1. Why do you need to retrieve the token in a way other than the `currentUser` API?

I've updated [my fork of the sample](https://github.com/palpatim/aws-mobile-appsync-events-starter-ios/tree/palpatim/gh-227-memory-leak) to use the most recent Pod versions, and to fix a bug in the refresh logic. Are you able to reproduce your issue using this sample, or an edit of it that supports your auth flow? (If you need to apply code edits, please note them in a PR or fork so I can try to repro using the same code.)

**Comment by uhive-genie9** [comment]
>1- What leads you to believe that it's the usage of a AWSCognitoUserPoolsAuthProvider that is causing the leaks? If you remove all of that code and test with an API_KEY auth mode, does the problem go away?

leaks are being introduced because of the usage of class instance which holds the  **AWSCognitoUserPoolsAuthProvider** in it, and then passing it to the **AWSAppSyncClientConfiguration**, its most likely to get retained because of strong referencing 


> 2-How exactly are you retrieving the access token from the server? If you're using a hand-rolled mechanism for retrieving the token, there may be a retain cycle in that code you're not seeing. In any case, making a network call to retrieve the token on demand, assuming it's properly isolated from other parts of the system and not retained (or retaining) in unexpected ways, should be doing largely the same thing my sample is doing. My sample uses the recommended API (currentUser().getSession()...) which may retrieve a cached result from the local device, but it does hit the network if the access token is expired

3-Why do you need to retrieve the token in a way other than the currentUser API?

in your sample code, you're using API key, well we are integrating the whole thing into a huge project and the requirements demands of using Cognito auth, for security reasons.
PS: not able to reproduce in your sample code.

would you mind inspecting our code and checking the flow we're using, i can share it privately to your email if possible

**Comment by uhive-genie9** [comment]
@palpatim  Any updates?

**Comment by palpatim** [comment]
@uhive-genie9 

I'm still not understanding the issue. Are you concerned that an instance of `AWSCognitoUserPoolsAuthProvider` is being retained? That is expected behavior; the client has to retain a reference to the provider so it can obtain credentials for new requests. 

> in your sample code, you're using API key, well we are integrating the whole thing into a huge project and the requirements demands of using Cognito auth, for security reasons.

As I mentioned above, I've modified the sample in [my fork](https://github.com/palpatim/aws-mobile-appsync-events-starter-ios/tree/palpatim/gh-227-memory-leak) to use a custom AWSCognitoUserPoolsAuthProvider, not API Key. So again, are you able to reproduce the issue by substituting your particular auth mechanism into the sample app? If not, that suggests the problem is somewhere in your app code, rather than in the SDK.

I'm happy to investigate a modified sample app, if you'd care to fork it and provide me access to a private repo, but I'd prefer not to attempt troubleshooting your custom app code.

**Comment by uhive-genie9** [comment]
we did fork the repo, and managed to reproduce the leaks, pull (https://github.com/palpatim/aws-mobile-appsync-events-starter-ios/pull/2)

**Comment by palpatim** [comment]
@uhive-genie9 

Thanks for the update, I'll investigate and reply as soon as I have more insight.

**Comment by palpatim** [comment]
@uhive-genie9 

I've spent several days with this now and am still unable to tie any leak behavior to the authentication mechanism.

## Test 1: Stripped-down subscription monitoring

**Methodology**
- Modified your linked fork of the sample app to use the AppSync "Chat" sample schema since you are using a custom schema to which I don't have access. (However, I don't expect this to change the app behavior unless there's something about the schema's Auth directives that are causing the behavior. If so, please see my "next steps" below for how you can provide a repro case.)
- Further modified the app to remove any UI, to remove any retains caused by the navigation/UIKit stack. I stripped out pretty much everything that wasn't involved in listening to subscriptions from the AppSync client. That includes UI (the modified app is just a blank screen), login/logout behavior (the new app simply returns a hardcoded access token value from the provider, just as yours does).
- Created two users in the app's user pool
- Logged in as User 1 to a web app running the [Angular sample](https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular)
- In the web page, started a conversation with User 2
- Obtain an access token for User 2 using the AWS CLI, totally outside the scope of any app code
- Pasted the value of the access token into the `UserPoolAuthProviderHelper`
- Launched the app, which authenticates as "User 2" using the hardcoded access token
- Monitored the app console for retrieved subscription results
- In the web app as User 1, sent messages in the conversation
- Monitored the console and verified that I received the incoming subscription messages
- Restarted the app using the Leaks instrument
- Ran the same test

**Debug Memory Graph Results**
- The `UserPoolAuthProviderHelper` is retained by `AWSAppSyncHTTPNetworkTransport`, as expected, since that class needs a reference to the authenticator every time it makes a call
- There are no repeated or unexpected instances of classes owned by the AWSAppSync module; each retained object has a single owner and an expected ownership path

**Leaks Instrument Results**
- There appears to be a retain cycle in Apollo's GraphQL executor/accumulator that is invoked during message processing. However, since the cycle is dropped if we cancel the subscription (see below), this is unlikely to be a real leak.
- Retained objects in `-[AWSIoTMQTTClient openStreams:]`, but it appears that it is retaining NSDate objects associated with the runloop invocation. This does not disappear when canceling the subscription. However, even replacing the associated NSDate with a `copy` of the date shows a retain of the date object. My assumption is that there is something internal to the runtime's runloop processing that is retaining the date, and is thus outside our control.
- Similarly, Leaks reports retains of NSDate objects in `[AWSIoTMQTTClient connectionAgeTimerHandler]`. Given that the AppSync client explicitly does not support reconnection behavior, this is a candidate for removal, along with all of the other unused reconnection logic. I've added #273 to our backlog for this.
- Intermittently, I see some reported leaks in SocketRocket's stream delegate (`-[AWSSRWebSocket stream:handleEvent:]`) but I can't reliably reproduce these, and my scan of the code doesn't indicate any likely suspects. Without some solid evidence that this is a cause of problems, I'm disinclined to pursue this further.

## Test 2: Cancel subscription and drop client

**Methodology**
Using the above client, modify the subscription handler to cancel the subscription, set the listener to `nil`, and set the AppSyncClient to `nil` after receiving 5 messages. If there are any legitimate retains, these would remain after releasing the client. (That doesn't mean there are no unbounded memory growth situations--if the AppSync client itself incorrectly retains objects after it is done processing, that could still cause issues, but this at least rules out things like self-referential retains.)

**Debug Memory Graph Results**
After the unsubscribe and release of the AppSyncClient:

- The only object associated with the AWSAppSync module is a retained SocketRocket thread. This is a static object, and thus would never be released. It's arguable that this is incorrect behavior; if the socket is closed, there's no particular reason we need to leave this thread hanging around, but at this point it appears innocuous
- Notably, there are no instances of any AWSAppSync objects (e.g., Auth objects, network transports, client, etc), nor the AmplifyHelper or AuthHelper itself.

Again, this doesn't completely clear AppSync from any invalid behavior or unbounded memory growth during normal operations, but it does rule out the client as a source of root leaks.

**Leaks Instrument Results**
- A 4KB allocation that passes through `-[AWSIoTMQTTClient disconnect]`. The referenced line is `self.clientDelegate = nil;`, which strikes me as an odd place to report a leak. I'm not sure what to make of this, especially since the debug memory graph results do not show any retained objects
- Each of the DB connections has a 64b allocation associated with it that passes through AWSSQLiteNormalizedCache `selectRecords(forKeys keys:)`. Since the Promise returned from that method is synchronously executed (that is, the closure is non-escaping), I'm not sure what to make of this. It's possible we need to investigate our SQLite termination code to ensure we are properly shutting down the connections (although my recollection is that simply setting the reference to `nil` should do that, and as mentioned, there do not appear to be any retained connections looking at the debug graph).

## Conclusion
I am unable to find any leaks associated with the authentication flow that you are reporting. Further, I'm unable to find any evidence to point to a serious unbounded growth behavior, although that may be due to differences in testing methodology. We know that memory usage and retains are heavily dependent on app implementations, so it's possible that the behavior you're seeing is due to some artifact of app handling, especially since I'm unable to replicate the behavior you show in the screenshots using the sample app fork you provided (again, modified to use a different schema).

Regarding your statement "The AWSOIDCAuthProvider protocol should be of class type or NSProtocolObject in order of its conforming instance to be weak and not to get allocated dozens of times": As noted, I haven't seen any evidence that doing so would actually change the retain behaviors you're reporting. Further, it's not unreasonable to expect an app developer to initialize the client with a "fire-and-forget" model:
- Init auth provider
- Pass auth provider to config initializer
- Pass config to AppSyncClient initializer
- Only retain the client

Weakening the references all down the chain would not only be a breaking change to the API, it would potentially break existing apps, which would now be responsible for retaining the authorizer well past the time they actually care about it.

Finally, I added some print statements to the `UserPoolAuthProviderHelper` init and deinit methods, and I only see each method invoked once, during appSyncClient initialization and release, as expected.

## Next Steps
Since I'm unable to reproduce your displayed behavior, with dozens of repro attempts across multiple variants of the sample code, and I'm unable to find a code path that would be implicated in the behavior you report, I'm not sure what else we can reasonably do.

In order to move forward, please provide a sample fork that demonstrates your issue with no code modifications. You can contact me via private channels to help me set up a test account with access to the API, so that the only change required to demonstrate the behavior is pasting the hardcoded access token into the `UserPoolAuthProviderHelper`.

Please let me know your thoughts.
