### ISSUE TITLE
Breaking changes in 'amplify codegen' ?

### ISSUE THREAD

**Issue by matthewbga** [awslabs/aws-mobile-appsync-sdk-ios#242]
**Describe the bug**
Running `amplify codegen --apiId <API ID>` creates a version of EventsAPI.swift that is not compatible with the demo at https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios.

I am drawing the conclusion that this _should_ work based on the reference in the documentation for this demo to the codegen docs.

**To Reproduce**
1. Setup the demo per instructions at https://github.com/aws-samples/aws-mobile-appsync-events-starter-ios
2. Run the demo. Verify it builds and works.
3. Retrieve the API ID from the Settings page of the AppSync API you created.
4. From the root directory of your project, run `amplify init`
5. From the root directory of your projects run `amplify codegen --apiID <API ID from above, #3>`, placing the generated API.swift in EventsApp/EventsAPI.swift.
6. In Xcode, build the project.
7. Note failure.

There are several build failures, including...
- Use of undeclared type 'Event'
- Use of undeclared type 'NewCommentOnEventSubscription'
- Value of type 'ListEventsQuery.Data.ListEvent.Item' has no member 'fragments'
- Use of unresolved identifier 'NewCommentOnEventSubscription'

**Expected behavior**
After running 1-6, above, the app builds and runs.

**Environment(please complete the following information):**
 - AppSync SDK Version: aws-cli/1.15.59
 - Dependency Manager: Cocoapods
 - Swift Version : 4.0
 - Amplify version: 1.6.3

**Device Information (please complete the following information):**
 - Device: Simulator (though does not matter)
 - iOS Version: 11.0
 - Specific to simulators:

**Comment by palpatim** [comment]
Need to replicate this locally to see whether this is an issue with AppSync code, sample code, or codegen.

**Comment by dougie181** [comment]
The example EventsAPI has the following at the bottom of the generated API that is not included when running the codegen process.
`public struct Event: GraphQLFragment {
...
}`

**Comment by lawmicha** [comment]
Thanks for reporting the bug here.

The sample app relies on the Events AppSync project to be created. I was able to do this successfully. I could not codegen based on steps shown on AppSync Console using Amplify CLI 3.9.0. I think there is a version mismatch between Amplify CLI and AppSync Console. Opened Issue here: https://github.com/aws-amplify/amplify-cli/issues/2472

Please track the issue on Amplify CLI team above;

If you would like to get the app running, I was able to by avoiding codegen since the codegen-ed file is checked into the sample app repo (EventsAPI.swift). The steps I had to take to get it running is:

1. `amplify init`
2. Download Config from AppSync console, place it under EventsApp/ folder
3. `pod install`
4. open EventsApp.xcworkspace
5. Build and run was successful, adding Event and Comments are persisting to DynamoDB.


Path going forward, we should first see where the codegen bug lands and then see if the newly generated file works in the sample app as is. If not, we can update the sample app with the newly codegen'd file, and remove it from source control so that new run throughs of the sample app will always use an generated file as it should be.

**Comment by lawmicha** [comment]
https://github.com/aws-amplify/amplify-cli/issues/2472 has been resolved, it was due to a codegen bug in 3.9.0. Upgraded to 3.11.0 and codegen works, however, adding it to the sample app does not and contains a bunch of errors.

I took a look at the sample app readme, and it actually doesn't specify you to do codegen, which is probably why EventsAPI is checked in and works with it.
