### ISSUE TITLE
Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

### ISSUE THREAD

**Issue by johnlietzke** [awslabs/aws-mobile-appsync-sdk-ios#310]
**Describe the bug**
Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)

**To Reproduce**
1. Install Pod
2. Compile in Xcode for swift

**Expected behavior**
No errors

**Environment(please complete the following information):**
 - AppSync SDK Version: 2.15.0
 - Dependency Manager: Cocoapods

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone11 Pro, Simulator]
 - iOS Version: [e.g. iOS 13.2]

**Comment by palpatim** [comment]
@johnlietzke You didn't include detail of where you're seeing the missing specifiers, but I'm assuming you're encountering the same issue as https://github.com/aws-amplify/aws-sdk-ios/issues/2001. If so, we're aware of the issue, and the fix is for us to go through and actually audit nullability requirements in the SDK, and then propagate those requirements as specifiers in the API.

If not, please reopen this issue and provide more detail around the specific issue you're encountering.

**Comment by johnlietzke** [comment]
Thanks for the reply. I know it does not effect the functionality of the pod but does bog down the debugger.  Any ETA on the update?

Thanks,
John

**Comment by palpatim** [comment]
No ETA as of now. We'll update the original issue when we have more info
