### ISSUE TITLE
Error initializing appsync client. invalidAuthConfiguration("API_KEY is selected in configuration but other providers are passed.")

### ISSUE THREAD

**Issue by zgao67** [awslabs/aws-mobile-appsync-sdk-ios#320]
I can't fix the error: Error initializing appsync client. invalidAuthConfiguration("API_KEY is selected in configuration but other providers are passed.")

I tried to add the code below, but doesnt seem to work. Please help 

extension AWSMobileClient: AWSCognitoUserPoolsAuthProviderAsync {
    public func getLatestAuthToken(_ callback: @escaping (String?, Error?) -> Void) {
        getTokens { (tokens, error) in
            if error != nil {
                callback(nil, error)
            } else {
                callback(tokens?.idToken?.tokenString, nil)
            }
        }
    }
}

extension ViewController: AWSCognitoUserPoolsAuthProvider {
    func getLatestAuthToken() -> String {
        let pool = AWSCognitoIdentityUserPool(forKey:"depressionappc552da46_userpool_c552da46-depression")
        let session =  pool.currentUser()?.getSession()
        return (session?.result?.idToken?.tokenString)!
    }
}

**Comment by Ricardo1980** [comment]
Can I see your awsconfiguration.json file?

**Comment by palpatim** [comment]
@zgao67 As the error indicates, your `awsconfiguration.json` configures AppSync with an `API_KEY` authorization type, but your configuration code is using some other authorization mode. Based on your code snippet above, it looks like you're using UserPools.

AWS AppSync does support the ability to use multiple authorization types on the same endpoint, for example to allow some queries to be available to unauthorized users, and some to be available to authorized users. In that case, using the Amplify CLI would allow you to set up a configuration for each authorization type, as described in the [mutli-auth documentation](https://aws-amplify.github.io/docs/sdk/ios/api#multi-auth)

If you are not trying to support that use case--that is, if your API should only be accessible by users who are registered and logged into your Cognito UserPool, then you should use the Amplify CLI to update your API's authorization type to be "Cognito UserPools" rather than API Key. Again, see the [API Documentation](https://aws-amplify.github.io/docs/ios/api#multi-auth) for a more in-depth discussion.

Hope this helps.
