### ISSUE TITLE
SQLlite  'try! failableNext()'

### ISSUE THREAD

**Issue by vincenzo-favara** [awslabs/aws-mobile-appsync-sdk-ios#322]
**Describe the bug**
My app does some fetch call, first is ok and randomly second call or other calls cause some crashes.

**Screenshots**
![crash](https://user-images.githubusercontent.com/48917328/70709958-6d486580-1cde-11ea-8c66-c2f66528b55e.png)

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.0.0
 - Dependency Manager: Cocoapods
 - Swift Version : 5

**Device Information (please complete the following information):**
 - Device: All
 - iOS Version: 13+
 - Specific to simulators: 13+

**Comment by lawmicha** [comment]
Hi @vincenzo-favara, thanks for reporting the issue, could you provide more details to reproduce this? which of the APIs are you using? which calls are you making when you see the issue? How often is it reproducible?

**Comment by Dachmian** [comment]
Hi @lawmicha, I have experienced the same issue.

Have not been able to reproduce myself but I have received crash reports with the same crash and call stack as the above screenshot. Same AppSync SDK version and iOS version.

From the reports it has happened while app is in background.

**Comment by vincenzo-favara** [comment]
I tried with different kind of call.
I have the same problem also after a mutation, app crashes after some seconds that call was success

**Comment by bmwalters** [comment]
I encountered this when my app had this scenario:

1. Initialize `AWSAppSyncClient` with on-disk cache configuration.
2. Some code runs that deletes the `FileManager.SearchPathDirectory.cachesDirectory` (bad)
3. AppSync attempts to store data to the on-disk cache, but the cache database was stored in the caches directory that has now been deleted.

Might want to make sure you aren't inadvertently deleting the database as well; you can test this by using `AWSAppSyncCacheConfiguration.inMemory` instead of the default.

**Comment by palpatim** [comment]
@bmwalters Thanks for your insights--the scenario you describe would definitely cause an issue. 

@vincenzo-favara AppSync defaults to the Caches directory, but provides a couple of options for overriding. One is `inMemory` as @bmwalters pointed out. This is useful for providing session-scoped caches where you don't care about persisting between app invocations. Another option would be for you to specify your own location, such as a subdirectory of the Documents directory  (`FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)`).

Do note that a best practice for storing AppSync cache data in the Documents Directory would be to [prevent it from being backed up to iCloud](https://developer.apple.com/library/archive/qa/qa1719/_index.html), since the data is transient and would needlessly consume user iCloud storage.

**Comment by vincenzo-favara** [comment]
@bmwalters thanks for your answer, I invastigated and the issue should be caused by that, but it's not accidentally, i want to signout and so delete all chached and data  from chache dir, so how can I do in safe mode? I want to leave the default conf.

**Comment by palpatim** [comment]
@vincenzo-favara rather than deleting the files, use the `clearCaches` method: https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/3.0.0/AWSAppSyncClient/AWSAppSyncClient.swift#L177

**Comment by vincenzo-favara** [comment]
Sorry @palpatim I explaned myself wrong, I need to delete the app cache, I'm not using just appsync, but also others

**Comment by vincenzo-favara** [comment]
I think you can close the issue, I figured out that issues is not correlated to appsync anymore after some code refactor.
