### ISSUE TITLE
Multiple AppSyncClients with separate AWSInfos

### ISSUE THREAD

**Issue by cody1024d** [awslabs/aws-mobile-appsync-sdk-ios#330]
I'd like to know the best practice for the following use-case.  Some of this is a bit simplified to better make sense in the AWS nomenclature:

Image a login screen where the user is asked to input his login/password/userPoolName.  This triggers the login process, which first verifies the input information (login/password/userPoolName), and then goes on to actually use the userpool to login.

This initial call is done via a graphQL call through the AppSyncClient.  Because this happens before login, this call can be used unauthenticated, and thus this first AppSyncClient needs to be configured in such a way that it does not require authentication.

After the login process, we need to create a new AppSyncClient, that has the associated user pool authentication provider to be used.

I'm a bit unsure on how to do this.  In thought, I should be able to build the ``awsconfiguration.json`` dynamically after login, and then use it to generate my second AppSyncClient.  However, what I'm concerned about, is that the first (unauthenticated) client may call to AWSInfo.default(), which would make that impossible (as AWSInfo's config cannot be updated).

**Edit**: Thinking of it, one way that it may be able to work is to custom implement the AppSyncServiceConfigProvider on the first AppSyncClient, so that it never hits AWSInfo....would that work?

Any help on this use-case would be great.

Thank you!

**Comment by lawmicha** [comment]
Hi @cody1024d

`awsconfiguration.json` gets read by `AWSInfo` which then a credentials provider like AWSMobileClient on initialization will use `AWSInfo`. This then gets passed to AppSync client's init. There is also a limitation with using more than one credentials provider after the app has launched because there is no way to reinstantiate AWSMobileClient as well. So even if you programatically init an AppSyncServiceConfigProvider, you still need to have two credentials provider, ie. AWSMobileClient for the first AppSync client and another for the second.

Could you use API key authentication for the first service since the unauth role is being used anyways? however, AppSync suggests that API key is only used for the development. APIGateway can also have an API key authorizer

**Comment by cody1024d** [comment]
Hey @lawmicha, thanks for the response!  I ended up reading a bit through the source code and seeing that ``AWSInfo`` class.  I read a bit deeper, and saw that it will not just willy-nilly call init on that class, and so, I was able to simply configure my login credentials AFTER calling the unauthenticated tenantInfo call.

Closing this, because it no longer reflects my use-case and thus I can't provide anymore additional details
