### ISSUE TITLE
AppSync 3.x should depend on AWSCore 2.13, not 2.12

### ISSUE THREAD

**Issue by sebsto** [awslabs/aws-mobile-appsync-sdk-ios#357]
**Describe the bug**
Using AppSync 3.x, the dependencies system installs AWSCore 2.12 and not the latest 2.13

**To Reproduce**
1. create the following pod file 
```
# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Landmarks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Landmarks
  pod 'AWSMobileClient', '~> 2.13'      # Required dependency
  pod 'AWSAuthUI', '~> 2.13'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.13'   # Optional dependency required to use drop-in UI
  pod 'AWSAppSync', '~> 3.0'           # For AppSync GraphQL API
  pod 'AWSS3', '~> 2.13'                # For file transfers
end
```

2. type `pod install` or `pod update`
and it fails with 
```
[!] CocoaPods could not find compatible versions for pod "AWSCore":
  In Podfile:
    AWSAppSync (~> 3.0) was resolved to 3.0.2, which depends on
      AWSCore (~> 2.12.0)

    AWSAuthUI (~> 2.13) was resolved to 2.13.0, which depends on
      AWSCore (= 2.13.0)
```

**Expected behavior**
I should be able to use AWSCode and co version 2.13 **and** AppSync 3.x together

**Environment(please complete the following information):**
 - AppSync SDK Version: 3.0.2
 - Dependency Manager: cocoapods
 - Swift Version : n/a

**Device Information (please complete the following information):**
 - Device: n/a
 - iOS Version: 13.x
 - Specific to simulators: n/a

**Comment by LachlanMcCulloch** [comment]
If conforming to semver, is it possible to tag version against `~2.13` rather than `~2.13.x` to allow updating without a new release in AWS Appsync?
From [here](https://guides.cocoapods.org/using/the-podfile.html):
> In addition to the logic operators CocoaPods has an optimistic operator ~>:
>
> '\~> 0.1.2' Version 0.1.2 and the versions up to 0.2, not including 0.2 and higher
> '\~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher
> '\~> 0' Version 0 and higher, this is basically the same as not having it.

**Comment by lawmicha** [comment]
Hi @sebsto ,

Please give it a try with AppSync 3.1.0, this contains a dependency on AWSCore 2.13. At the moment, we follow up an AppSync dependency upgrade once AWSCore minor versions are released, and the delayed AppSync release is why the current AppSync version does not work with existing iOS SDK's latest version (2.13). We have some on-going discussions to see how we can make this better.

> If conforming to semver, is it possible to tag version against `~>2.13` rather than `~>2.13.x` to allow updating without a new release in AWS Appsync?
> From [here](https://guides.cocoapods.org/using/the-podfile.html):
> 
> > In addition to the logic operators CocoaPods has an optimistic operator ~>:
> > '~> 0.1.2' Version 0.1.2 and the versions up to 0.2, not including 0.2 and higher
> > '~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher
> > '~> 0' Version 0 and higher, this is basically the same as not having it.

Thanks for the details @LachlanMcCulloch, this could be an issue as AWSCore does not conform to semver. When AppSync had updated to take on 2.13, it had code changes due to 2.12 to 2.13 containing breaking changes. Once the iOS SDK conforms to semver, then we could go with ~>2.13 to take 2.13 up and not including version 3.
