### ISSUE TITLE
3.0.2 doesn't compile

### ISSUE THREAD

**Issue by bsarrazin** [awslabs/aws-mobile-appsync-sdk-ios#358]
**Describe the bug**
3.0.2 doesn't compile

**To Reproduce**
1. Install 3.0.2
2. Compile

**Expected behavior**
3.0.2 should compile

**Additional context**

`OIDCBasedConnectionPool.swift:34:52: Use of unresolved identifier 'RealtimeGatewayURLInterceptor`
`connectionInterceptable.addInterceptor(RealtimeGatewayURLInterceptor())`

**Comment by lawmicha** [comment]
hi @bsarrazin thanks for reporting this issue, this issue occurred when i published a dependency of AppSyncClient that had a breaking change as a patch version. I have already removed the patch version pod since tuesday March 10th, could you give it a try and let us know if you are still seeing any issues? 3.1.0 has also been released
