### ISSUE TITLE
AWSNetworkTransport Error when initializing AWSAppSync in AppDelegateFile SwiftUI - Xcode 13.1 

### ISSUE THREAD

**Issue by tyler125brown** [awslabs/aws-mobile-appsync-sdk-ios#502]
Swift Packet Dependency, Next Version up. Version 3.4.1 I think. The AWSAppSyncClientConfiguration(appSyncServiceConfig: as for a parameter of AWSNetWorkTransport and 
there is no reference. May be the reason it is not initializing?

**Comment by royjit** [comment]
Please provide the following information to debug further:
---

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment(please complete the following information):**
 - AppSync SDK Version: [e.g. 2.6.21]
 - Dependency Manager: [e.g. Cocoapods, Carthage]
 - Swift Version : [e.g. 4.0]

**Device Information (please complete the following information):**
 - Device: [e.g. iPhone6, Simulator]
 - iOS Version: [e.g. iOS 11.4]
 - Specific to simulators:

**Additional context**
Add any other context about the problem here.

**Comment by tyler125brown** [comment]
Environment:
Xcode 13.1
Swift 5.5
Dependency Manager: Swift Package Manager
No Device needed, error shows up in the IDE

1.) Download AppSync through the Xcode Swift Package Manager using the next "next major".
2.) Close the app and then reopen it.

This error appears.
<img width="708" alt="Screen Shot 2021-11-28 at 7 49 58 PM" src="https://user-images.githubusercontent.com/21092345/143806372-4a821e14-e4a8-43ef-b918-31a7d3f53a3d.png">

Based on all of the guides. This should not be the format for initialization. Thank you! @royjit  for taking the time to look at this.

**Comment by tyler125brown** [comment]
Okay so the problem occurs when we try to include awsappsync and firebasefirestore into the same project. I am unsure as to why this causes so many errors. I need for this to stop! It is causing many problems in our project! I have tried many things including clearing derived data to try to prevent the error. The error does not stop the build from running and I would love if you could look into why the awsappsyc app has these additional calls that cannot be found.
